title: Thiago Corrêa
author: Thiago Corrêa
url: https://correadeoliveira.com # root address of the site
description: > # description of the site (multiple lines allowed)
  "Writing is the structure of thinking, here I write everything that I think."

permalink: /:slug/

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: abhinav # update or delete this
    card: summary_large_image

future: true # Adicione esta linha para publicar posts com data futura

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # pode ser "light", "dark" ou "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "início.." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: false # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # mostra projetos como cards, adicione em _data/home.yml
  show_blog: false # show blog posts added in _posts
  show_old_projects: false # mostra projetos antigos como cards, adicione em _data/home.yml
  show_misc_list: false # mostra lista vertical genérica para detalhes, adicione em _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Artigos
    title_misc_list: Detalhes
    title_blog: Blog
    title_old_projects: Projetos Antigos

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
